### ISSUE TITLE
Handle command count in error message

### ISSUE THREAD

**Issue by Okibe00** [matshidisolp/simple_shell#29]
The command count variable will keep a count of the number times a command has been giving to the shell, This count will be added to the error message when its being printed in any function.
## General format of error message
`program_name: command_count: command: error`
```
$ echo "qwerty" | ./hsh
./hsh: 1: qwerty: not found
$ echo "qwerty" | ./././hsh
./././hsh: 1: qwerty: not found
$
```

**Comment by matshidisolp** [comment]
close
